### PR TITLE
Initialised Docusaurus

### LINKED ISSUE #1: Initialise Docusaurus

### PR DESCRIPTION
**Pull request by sarthakkundra**
Classic themed boilerplate.

Closes #1

### CODE REVIEW

**Comment by sarthakkundra** [comment]
@Tlazypanda I've also setup the project board with some initial issues, you can take a look and probably move this to `review-done` column.

**Review by Tlazypanda — APPROVED** [review]
@sarthakkundra LGTM! :tada: Merge away :v:

**Comment by Tlazypanda** [comment]
@sarthakkundra Don't have access to move the project board cards yet maybe @aornugent can help

**Comment by sarthakkundra** [comment]
@Tlazypanda I've added you as a maintainer. You should be able to see it now.

**Pull request merged**
