### PR TITLE
Add eslint and prettier configuration and run the intial check

### LINKED ISSUE #2: Setup ES-Lint and Prettier
To follow standard coding conventions all along the project, let's setup a pre-commit hook using ES-Lint and Prettier. 

Refer [article](https://medium.com/dubizzletechblog/setting-up-prettier-and-eslint-for-js-and-react-apps-bbc779d29062) for any guidance.

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixes #2
Add eslint and prettier configuration and run the intial check to fix some problems.

@sarthakkundra

### CODE REVIEW

**Comment by sarthakkundra** [comment]
Hey @Abhishek-kumar09 . Looks good. Can you please remove the `package-lock` file. That will automatically be added when anyone runs `npm install` so no need to include it in the bundle.

**Comment by Abhishek-kumar09** [comment]
I added some packages, that's why there is change in lock file. But if you want I can remove it.

**Comment by aornugent** [comment]
@sarthakkundra is this ready for merge?

**Comment by sarthakkundra** [comment]
@aornugent It is but I'm keeping it on hold, before I merge the homepage so that we have some code to check the linting on.

**Pull request merged**
