### PR TITLE
Added github-issue labeller ci

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

Partially_Fixes: #8 

Added needs-triage automatic issue labeller.

[Try it yourself by creating a new issue](https://github.com/Abhishek-kumar09/contributor-website-v2/issues)

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
@all-contributors please add Abhishek-kumar09 for infra

**Comment by Abhishek-kumar09** [comment]
@all-contributors please add @Abhishek-kumar09 for infra

**Comment by sarthakkundra** [comment]
@Abhishek-kumar09 Will you be adding the action to add label as well?

**Comment by Abhishek-kumar09** [comment]
> Will you be adding the action to greet first PR as well?

I had did it in some previous Repo, the marketplace actions have some issues.
Have to make a new github action for this or atleast would have to see a different option.

**Comment by sarthakkundra** [comment]
Great work @Abhishek-kumar09. If you wish to pick up the remaining work, please let me know on the issue itself. Thanks!x

**Pull request merged**
